version: '3.7'

services:
  newman:
    image: postman/newman
    volumes:
      - ./api-test/API Test.postman_collection.json:/etc/newman/collection.json
      - ./api-test/API Test.postman_environment.json:/etc/newman/environment.json
      - ./api-test/data.json:/etc/newman/data.json
      - ./api-test/report:/etc/newman/report
      - ./api-test/entrypoint.sh:/entrypoint.sh
    entrypoint: /bin/sh /entrypoint.sh

  cypress:
    image: cypress/included
    volumes:
      - ./ui-test:/e2e
      - ./ui-test/report:/e2e/report
    working_dir: /e2e
    environment:
      - WEB_URL=${WEB_URL}
    entrypoint: /bin/sh -c "npm install mochawesome && cypress run --spec 'cypress/e2e/crud.cy.js' --browser edge --reporter mochawesome --reporter-options reportDir=/e2e/report,overwrite=true,html=true,json=true"
    networks:
      - web

  k6:
    image: grafana/k6
    volumes:
      - ./load-test/test.js:/scripts/test.js
      - ./load-test/report:/results
    environment:
      - API_URL=${API_URL}
    entrypoint: /bin/sh -c "k6 run /scripts/test.js --summary-export=/results/summary.json"

networks:
  web:
    external: true
